# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# we are not building Visual Studio project, so default build step is off
build: off

# encrypting data done here: https://ci.appveyor.com/tools/encrypt
environment:
  PYPIPASS:
    secure: Bq/BLSOSlZhPmHsWR1ML1A==
  PYPIUSER: grzanka

  matrix:
#    # http://www.appveyor.com/docs/installed-software#python
    - platform: x86
      PYTHON_ROOT: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      MINICONDAPATH: "C:\\Miniconda"

init:
- git --version
- "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""

test: off
